use KVO_UNIVER;


select distinct PULPIT.PULPIT_NAME
from PULPIT, PROFESSION
where PROFESSION.FACULTY = PULPIT.FACULTY and PROFESSION.PROFESSION_NAME 
in (select PROFESSION.PROFESSION_NAME from PROFESSION where (PROFESSION_NAME like('%òåõíîëîã%')));


select distinct PULPIT.PULPIT_NAME
from PULPIT inner join PROFESSION
on PULPIT.FACULTY = PROFESSION.FACULTY
where PROFESSION.PROFESSION_NAME
in (select PROFESSION.PROFESSION_NAME from PROFESSION where (PROFESSION_NAME like('%òåõíîëîã%')));


select distinct PULPIT.PULPIT_NAME
from PULPIT 
inner join FACULTY
on FACULTY.FACULTY = PULPIT.FACULTY
inner join PROFESSION
on PROFESSION.FACULTY = PULPIT.FACULTY
where PROFESSION.PROFESSION_NAME
in (select PROFESSION.PROFESSION_NAME from PROFESSION where PROFESSION_NAME like('%òåõíîëîã%'));


select AUDITORIUM_CAPACITY, AUDITORIUM_TYPE
from AUDITORIUM a
where AUDITORIUM_NAME = (select top(1) AUDITORIUM_NAME from AUDITORIUM aa where aa.AUDITORIUM_TYPE = a.AUDITORIUM_TYPE order by AUDITORIUM_CAPACITY desc);


select FACULTY_NAME
from FACULTY
where not exists (select PULPIT_NAME from PULPIT where PULPIT.FACULTY = FACULTY.FACULTY);


select top(1)
(select avg(NOTE) from PROGRESS where PROGRESS.SUBJECT like 'ÎÀèÏ') [ÎÀèÏ],
(select avg(NOTE) from PROGRESS where PROGRESS.SUBJECT like 'ÁÄ') [ÁÄ],
(select avg(NOTE) from PROGRESS where PROGRESS.SUBJECT like 'ÑÓÁÄ') [ÑÓÁÄ]
from PROGRESS;


select AUDITORIUM_NAME, AUDITORIUM_CAPACITY
from AUDITORIUM
where AUDITORIUM_CAPACITY >= all(select AUDITORIUM_CAPACITY from AUDITORIUM where AUDITORIUM_NAME like '3%');



select AUDITORIUM_NAME, AUDITORIUM_CAPACITY
from AUDITORIUM
where AUDITORIUM_CAPACITY >= any(select AUDITORIUM_CAPACITY from AUDITORIUM where AUDITORIUM_NAME like '3%');


select NAME,BDAY
from STUDENT a
where (select count(*) from STUDENT aa where aa.BDAY = a.BDAY) > 1 order by BDAY desc ;